2019-07-30 14:08:17,239 ERROR: Exception on /register [GET] [in /home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sanya/microblog/app/routes.py", line 92, in register
    return render_template('register.html', title='Register', form=form)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/sanya/microblog/app/templates/base.html", line 38, in template
    {% block content %}{% endblock %}
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/sanya/microblog/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/sanya/microblog/app/templates/base.html", line 38, in template
    {% block content %}{% endblock %}
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/home/sanya/microblog/venv/lib/python3.6/site-packages/jinja2/compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-07-30 14:09:47,561 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:18:50,326 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:23:47,040 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:27:10,320 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:38:05,832 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:38:49,718 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:39:43,627 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 14:41:07,450 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:00:37,727 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:01:58,340 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:03:10,025 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:04:14,196 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:08:53,314 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 15:11:48,216 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-30 21:44:41,573 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:49]
2019-07-31 01:24:01,221 INFO: Microblog startup [in /home/sanya/microblog/app/__init__.py:51]
